### ISSUE TITLE
Trained files

### ISSUE THREAD

**Issue by AndreJFBico** [tonypeng/tensorstyle#2]
Hi could you provide a link to an already trained .pb or a set of .ckpt files.

The training process is taking forever to achieve a good result(500+ iterations), id like to proceed with an already trained model if you still have it lying around.

**Comment by tonypeng** [comment]
Hi Andre,

I've been traveling in Asia for the past week and a half, so if you still want the files I can certainly try and look for them!

**Comment by AndreJFBico** [comment]
Thanks!

 Its no longer necessary ive found a few other pre trained models that work with a similar network to the one you use for inference.
